### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by brianprichardson** [trebledawson/chess#1]
Hello.  I am trying to run your project and encountering some hopefully minor procedural issues.  A few minutes of your time updating the readme with the steps and a requirements.txt file would be most appreciated.  I am able to run neural_network.py and create the model files, but when I tried cleaning.py with a pgn file I supplied see below.  I have a GTX 1070 with 8GB and hope the model with 30+MM parameters can be accommodated.
Thanks

For example, what version of python-chess?  The current one gives me this:
Traceback (most recent call last):
  File "cleaning.py", line 13, in <module>
    poss = all_possible_moves()
  File "/home/brianr/chess/tools.py", line 139, in all_possible_moves
    board1 = chess.Bitboard()
AttributeError: module 'chess' has no attribute 'Bitboard'

**Comment by trebledawson** [comment]
My apologies, I honestly had not expected anyone else to ever attempt to run this program.

The data file I used was GMallboth.pgn, which can be downloaded for free from chess-db.com.

The version of python-chess is 0.4.1, since that is the most recent version that would play nice with my Anaconda environment.

Your GPU should be more than capable of handling the 30 million parameter model; my laptop's GTX 1050 Ti was capable of handling it (in fact it was the limiting factor in terms of neural network size).

I will update the README accordingly. Thank you for your interest in my project; I would be very interested to know how it runs on your machine, and if you make any improvements to the design.

**Comment by brianprichardson** [comment]
Created a venv for the ancient python-chess :)
Running cleaning.py on the pgn file.

What is the next step?
Thanks

**Comment by trebledawson** [comment]
After finishing with the cleaning file, you should be able to simply run GM_training.py. In theory, this will train the network to play at or around human grandmaster level. In practice, the performance of the model will be significantly lower. In fact, in my experiments, the model underfitted the value output; because of this, I concluded that the network was too small, and since the network was already as large as I could make it, I abandoned the project. I may resume development when I obtain bigger hardware, or if someone else is able to obtain more positive results. 

Note that the MCTS as I have implemented it is extremely slow; a major limiting factor in the training process is the number of MCTS simulations run in a given time span, and since my implementation is pure Python, it's quite inefficient. If you want to try using the Cythonized versions of certain functions relating to the MCTS, comment/uncomment the appropriate lines in the header of parallel_self_play.py. 

Essentially, I would recommend keeping your expectations low for this particular implementation, but if you want to use some of the ideas in it then feel free to explore. I would be very interested to see where this can go with more expertise.

**Comment by brianprichardson** [comment]
Thanks.  So far so good.

BTW I'm still a Linux noob so what does the filename/directory format used mean:
.\Data\xxx

That is, dot backslash Data backslash.  Tried looking and backslash seems to usually be an escape char.

**Comment by trebledawson** [comment]
This project was developed on Windows, so the file directories are indexed accordingly. You may need to adjust some directory names to work in other OSes such as Linux.

**Comment by brianprichardson** [comment]
Ah.  I just didn't want to run cleaning for a long time generating all of those files and have them disappear as tmp or something like that.

**Comment by trebledawson** [comment]
The files should be generated as .pickle files in the local Data subdirectory.

**Comment by brianprichardson** [comment]
Yup.  Started a small test training session with only the first 25 pickle files.  Each epoch takes about 3 sec on my GPU.  I noticed the tensorboard callback but it does not show anything yet, BTW.  This make take some time, which is OK.
